INSERT INTO public.question_translation (question_id, question_text, language) VALUES (1, 'Как, где и с кем Вы отметили Новый год?', 'ru');-----------------ЯНВАРЬ-----------------
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (2, 'Какая у меня цель на этот год?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (3, 'Какой длины у Вас сейчас волосы?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (4, 'В какую неловкую ситуацию Вы недавно попали?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (5, 'Где Вы живете?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (6, 'Из чего состоит идеальный день?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (7, 'Кем Вы хотите быть?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (8, 'Какую неудачную покупку Вы совершили за последнее время?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (9, 'Что лежит сейчас в вашем холодильнике?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (10, 'Где Вы работаете?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (11, 'Вы популярны?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (12, 'Ваш главный недостаток?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (13, 'Кто сейчас президент?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (14, 'Какую глупую вещь Вы сегодня совершили?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (15, 'Жизнь справедлива? Да? Нет? Не сегодня?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (16, 'Ваш девиз...', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (17, 'В выходные Вы обычно занимаетесь...', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (18, 'Вы скучаете по...', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (19, 'Вы хотите новый...', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (20, 'Сколько чашек кофе Вы сегодня выпили?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (21, 'Люди могут меняться?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (22, 'Ваша любимая песня?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (23, 'Вы хотите быть походим на...', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (24, 'Какое самое большое препятствие сейчас перед вами?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (25, 'Последний раз Вы очень сильно смеялись, когда...', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (26, '3 правила успеха...', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (27, 'Ваш доход сейчас...', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (28, 'По шкале от 1 до 10 насколько вам сейчас грустно? Почему?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (29, 'Ваш любимый аксессуар - это...', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (30, 'С кем из коллег у Вас самые хорошие отношения?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (31, 'Что сегодня произошло важного?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (32, 'Карьера или семья?', 'ru');-----------------ФЕВРАЛЬ-----------------
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (33, 'Что бы Вы хотели узнать о своем будущем?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (34, 'Каким видом спорта Вы сейчас занимаетесь?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (35, 'Что Вы хотите получить на день рождение?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (36, 'Какой комплимент вам сегодня сделали?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (37, 'Что лежит в вашей сумке?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (38, 'Какое качество самое важне в вашем партнере?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (39, 'Лучшее время в вашей жизни?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (40, 'Почему Вы живете там, где сейчас живете?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (41, 'Сегодня Вы больше всего нуждаетесь в...', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (42, 'Какой ваш вес?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (43, 'Вы должны кому-то деньги? Или кто-то должен вам?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (44, 'Лучшая часть сегодняшнего дня?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (45, 'Вы влюблены?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (46, 'Какой ваш самый безумный поступок, совершенный ради любви?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (47, 'Ваше рецепт для лечения разбитого сердца?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (48, 'Какая у Вас должность?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (49, 'Насколько здоровым Вы себя ощущаете, от 1 до 10?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (50, 'Вы сейчас обижены? Если да, то на кого?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (51, 'Самая стильная вещь в вашем гардеробе - это...', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (52, 'Вам сейчас хочется покоя или приключений?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (53, 'Настоящий человек должен...', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (54, 'Возможна ли дружба с противоположным полом?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (55, 'Вы лидер или исполнитель?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (56, 'Какая сегодня погода?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (57, 'Что Вы сейчас читаете?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (58, 'Опишите ваше последнее ночное приключение...', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (59, 'Сколько денег наличными в вашем кошельке? А на банковском счете?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (60, 'В каком ресторане Вы были в крайний раз?', 'ru');-----------------МАРТ-----------------
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (61, 'Каких тем Вы стараетесь избегать?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (62, 'Какая песня застряла у Вас в голове?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (63, 'Сегодня было весело потому что...', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (64, 'Какое представление или концерт Вы посетили за последнее время?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (65, 'Какой интересный случай произошел с вами сегодня?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (66, 'Каким талантом Вы бы хотели обладать?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (67, 'Что вам подарили на 8 марта?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (68, 'Если бы пришлось выбирать из того, что делает Вас счастливым, какую одну вещь Вы бы выбрали?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (69, 'Кому Вы крайний раз подарили что-то без повода?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (70, 'Что бы Вы хотели избежать в отношениях?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (71, 'Сегодня был трудный день потому что...', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (72, 'Сможете ли Вы простить измену?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (73, 'Без какого изобретения человечества Вы не смогли бы жить?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (74, 'Самая дорогая вещь на Вас сейчас - это...', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (75, 'На сколько красивым Вы себя ощущаете, от 1 до 10?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (76, 'Интересный факт, который Вы недавно узнали?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (77, 'Что интересного сегодня произошло?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (78, 'Как бы Вы могли в трех словах описать вашу личную жизнь?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (79, 'О чем Вы сегодня мечтали?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (80, 'Когда крайний раз Вы были в кинотеатре?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (81, 'Какой марки одежду Вы в основном покупаете?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (82, 'На что вам не хватает денег?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (83, 'С кем бы Вы хотели поменяться местами на один день?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (84, 'Когда в крайний раз Вы ели фастфуд?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (85, 'Что Вы любите делать в воскресенье утром?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (86, 'Ваш главный принцип жизни...', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (87, 'Сколько времение в день Вы тратите на телефонные разговоры и личную переписку?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (88, 'Что можно купить на 100 рублей?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (89, 'Где Вы хотите жить?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (90, 'Ваш лучший друг - это...', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (91, 'Самый смешной розыгрыш за сегодня?', 'ru');-----------------АПРЕЛЬ--------------------------------------------
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (92, 'Самый привлекательный актер?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (93, 'Плохая идея - эксперементировать с...', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (94, 'Если бы в ваш день можно было добавить один час, на что бы Вы его потратили?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (95, 'У Вас много свободного времени?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (96, 'На чьей свадьбе Вы присутствовали в крайний раз?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (97, 'Что Вы ели сегодня утром?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (98, 'Сколько детей Вы хотите иметь?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (99, 'Над чем Вы работаете в данный момент?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (100, 'Три слова, которые описывают ваше состояние сейчас...', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (101, 'Вы могли бы сделать пластическую операцию?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (102, 'Вам нужен перерыв? Зачем?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (103, 'Какие дествие мечты Вы не воплотили в жизнь?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (104, 'С какой знаменитостью Вы бы хотели поужинать?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (105, 'Какое слово-паразит Вы сейчас используете?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (106, 'О какой работае Вы мечтаете?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (107, 'Кто Вас вдохновляет?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (108, 'Что Вы хотите купить?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (109, 'Какое кино Вы недавно посмотрели?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (110, 'Вы оригинальный человек? Почему?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (111, 'Какое место на Земле можно название райским?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (112, 'Как Вы можете описать свое поведение на работе?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (113, 'Когда крайний раз Вы болели?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (114, 'Вы оптимист или пессимист?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (115, 'Что нового Вы попробовали сегодня?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (116, 'Ваш идеал/авторитет - это...', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (117, 'Какой цвет в одежде Вы предпочитаете?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (118, 'Что бы Вы хотели забыть?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (119, 'У какой знаменитости Вы бы хотели взять интервью?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (120, 'Больше всего Вы благодарны за...', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (121, 'Какие дела Вы хотите отложить на потом?', 'ru');-----------------МАЙ-----------------
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (122, 'Какой момент из сегодняшнего дня Вы хотели бы переиграть?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (123, 'Кого вам больше всего не хватает сейчас?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (124, 'Вам хочется кому-то отомстить?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (125, 'Кто самый яркий человек в вашей жизни?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (126, 'Если бы завтра Вы могли отправится в путешествие куда угодно, какое место Вы бы выбрали?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (127, 'К кому Вы чувствуете сегодня признательность?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (128, 'На что вам не хватает времени?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (129, 'Новое блюдо, которое Вы научились готовить, - это...', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (130, 'Какой поступок меня поразил?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (131, 'Вы на верном пути?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (132, 'Кто должен сыграть Вас в фильме про вашу жизнь? Какого жанра этот фильм?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (133, '5 людей, с которыми я больше всего общаюсь...', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (134, 'Какого домашнего питомца Вы хотите завести?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (135, 'Когда и с кем за последнее время у Вас был самый интересный разговор?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (136, 'Без какой вещи Вы не можете выйти из дома?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (137, 'Вы цинник или метчтатель?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (138, 'Когда и при каких обстоятельствах крайний раз Вы выступали перед аудиторией?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (139, 'На что я трачу слишком много времени?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (140, 'Что хочется запомнить из сегодняшнего дня?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (141, 'Какой ваш рост в см?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (142, 'Довольны ли Вы вашей жизнью? От 1 до 10..', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (143, 'Если бы вам осталось один день, с кем и как я бы его провела?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (144, 'Куда бы я отправилась на машине времени?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (145, 'Как бы Вы хотели встретить старость?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (146, 'Где и когда крайний раз Вы плавали?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (147, 'Если бы сегодня у Вас не было никаких дел, чем бы Вы занялись?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (148, 'На какую вечеринку Вы последний раз ходили?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (149, 'Какого цвета твои глаза и как они сочетаются с твоим настроением?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (150, 'Когда Вы крайний раз были на свидании?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (151, 'Какой он, отпуск вашей мечты?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (152, 'Как долго принимаю решения?', 'ru');-----------------ИЮНЬ-----------------
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (153, 'Какой журнал или газету Вы регулярно читаете?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (154, 'За что Вас ценит начальник?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (155, 'Какие проблемы волновали Вас серьезно?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (156, 'Что необычное лежит в вашей сумке?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (157, 'Когда Вы в крайний раз плакали?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (158, 'Сегодняшний день был заурядным? Почему?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (159, 'Вы доверяете своим инстинктам?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (160, 'Какой музыкальный исполнитель сейчас самый популярный?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (161, 'Какого размера Вы покупаете одежду?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (162, 'Когда крайний раз Вы встречались с друзьями?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (163, 'У вас есть тайная страсть? Какая?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (164, 'Как Вы любите проводить вечера пятницы?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (165, 'Вы считаете, что вы похожи на этого литературного героя...', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (166, 'С кем из знакомых Вы хотели бы стать друзьями?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (167, 'Во сколько обычно вы встаете по будням?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (168, 'Идеальные выходные - это когда...', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (169, 'Как обычно вы начинаете будний день?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (170, 'Кого вы считаете милым?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (171, 'Что делает вас несчастным?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (172, 'Кто ваш лучший друг?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (173, 'Ваша самая большая проблема сейчас - это...', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (174, '... поднимает вам настроение.', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (175, 'Какими духами вы пользуетесь последнее время?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (176, 'Сегодня был восхитительный день, потому что...', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (177, 'Что вы хотели сделать, но не сделали и сейчас жалеете?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (178, 'Вы целовались сегодня? Если да, то с кем?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (179, 'Какая зарплата вас бы устроила?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (180, 'Если бы вы могли иметь супер силу - чтобы это было?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (181, 'Когда крайний раз вы летали на самолете?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (182, 'Чтобы вы хотели знать лучше?', 'ru');-----------------ИЮЛЬ-----------------
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (183, 'Что было в последнем личном письме, которое вы получили?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (184, 'Что вам больше всего нравится в вашем теле?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (185, 'За что меня ценят мои друзья?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (186, 'Когда вы последний раз отдыхали?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (187, 'Чем вы сегодня занимались?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (188, 'Ваша недавняя штука, которая всех расмешила?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (189, 'Вас легко вывести из себя?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (190, 'Ваш враг №1?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (191, 'Как бы вы подвели итоги этого дня в одном предложения?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (192, 'Какое необычное блюдо вы пробовали?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (193, 'У вас появились новые друзья?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (194, 'Если вы оглянитесь прямо сейчас, что вы увидете?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (195, 'Какую сферу жизни вы хотите изменить?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (196, 'Сколько денег вы в месяц вы тратите на развлечения?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (197, 'Ваша любимая одежда...', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (198, 'Какую роль вы бы хотели исполнить в кино или театре?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (199, 'Долго ли вы собираетесь на работу?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (200, 'Классика или casual?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (201, 'Какие три сайта вы посещаете чаще всего?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (202, 'Кто вы?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (203, 'Что может поднять вам настроение прямо сейчас?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (204, 'Что вам нравится в вашей работе?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (205, 'Какое самое умное слово вам сейчас пришло в голову?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (206, 'Чтобы произвести впечатление на нового знакомого, вы...', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (207, 'Ваша первая мысль с утра...', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (208, 'Кому вы завидуете?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (209, 'Что вас сегодня расстроило?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (210, 'Вы предпочли бы жить в центре города или загородом?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (211, 'Что способно вас растрогать?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (212, 'У вас дома порядок?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (213, 'Какой ваш любимый гаджет?', 'ru');-----------------АВГУСТ-----------------
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (214, 'За какую команду вы болетее? (любой вид спорта)', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (215, 'Какое блюда в последний раз кто-то приготовил для вас?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (216, 'Чтобы вы хотели получить в подарок от любимого человека?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (217, 'Вы умный человек? По шкале от 1 до 10.', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (218, 'Чего вы больше всего боитесь?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (219, 'Какие 5 вещей вы бы взяли с собой на необитаемый остров?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (220, 'Чувствуете ли вы себя одинокой?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (221, 'Где вы видете себя через год?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (222, 'Лучшая новость сегодняшнего дня...', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (223, 'Что вас раздражает в людях?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (224, 'Как бы вы могли описать свой образ?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (225, 'Первое слово пришедшее на ум?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (226, 'Сколько времени вы проводите в социальных сетях?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (227, 'Что вам необходимо выбросить?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (228, 'От кого вы бы хотели сейчас получить смс?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (229, 'Сколько денег вы готовы потратить на одежду?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (230, 'Сколько времени вы тратите на сон?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (231, 'Кто вас сегодня разозлил?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (232, 'Что нужно делать чтобы достичь желаемого?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (233, 'Ваша слабое место - это...', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (234, 'Ваши планы на завтра...', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (235, 'Ваш секрет?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (236, 'Чем вы сейчас одержимы?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (237, 'Когда последний раз вы ели пиццу? С чем она была?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (238, 'Если когда-нибудь о вас напишут книгу, какое название у нее будет?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (239, 'Сколько времени вы тратите на дорогу до работы?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (240, 'У вас есть талисман?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (241, 'План или импровизация?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (242, 'Когда вам чаще всего приходят в голову хорошие идеи?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (243, 'Самое классное что произошло этим летом?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (244, 'Сколько денег вы потратили на свой последний отпуск?', 'ru');-----------------СЕНТЯБРЬ-----------------
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (245, 'Что может вывести вас из себя?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (246, 'Любовь это...', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (247, 'Что у вас на ужин?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (248, 'Вы устали от своей работы?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (249, 'Какой недавно просмотренный фильм вы бы не стали рекомендовать друзьям?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (250, 'Какие шокирующие новости вы недавно узнали?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (251, 'Вам не хватает терпения для...', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (252, 'Вы бы не хотели что бы вам сейчас было ... лет, потому что...', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (253, 'Какие мысли вас преследуют в данный момент?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (254, 'Как бы вы могли в трех словах описать свою работу?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (255, 'От кого последний пропущенный звонок на телефоне?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (256, 'Как бы ваш друг описал вас в трех словах?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (257, 'В скольких странах вы были?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (258, 'Что вы считаете своим самым большим достижением?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (259, 'На что вы тратите слишком много денег?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (260, 'На что вы первым обращаете внимание при встрече с незнакомым человеком?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (261, 'Ваш рецепт хорошего настроения?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (262, 'Если бы вы мошли повернуть время вспять, что бы вы изменили?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (263, 'Вы нашли доказательства существования высшей силы?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (264, 'Когда вы последний раз употребляли алкоголь?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (265, 'Что приносит вам самое большое наслаждение?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (266, 'Вы умеете говорить "нет"?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (267, 'Сегодня был забавный день, потому что...', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (268, 'В какой профессии вы бы хотели себя попробовать?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (269, 'Что должно остаться как есть?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (270, 'С чем/кем связаны самые приятные воспоминания?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (271, 'Плохие новости: лучше приукрасить или выложить как есть?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (272, 'Вы часто врете?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (273, 'Во сколько вы легли спать прошлой ночью?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (274, 'Какой вы видите себя через год?', 'ru');-----------------ОКТЯБРЬ-----------------
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (275, 'Кто самый важный человек в вашей жизни?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (276, 'Что вы считаете непреодолимым?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (277, 'Кем бы вы хотели быть в следующей жизни?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (278, 'Когда последний раз вы выезжали за город?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (279, 'Можете ли вы первым заговорить/познакомиться с незнакомым человека?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (280, 'Какая песня вас характеризует?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (281, 'В еде вы злоупотребляете...', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (282, 'Последний спонтанный поступок? Какие последствия?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (283, 'У вас есть любимы человек?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (284, 'В чем секрет успешных любовных отношений?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (285, 'Шутка дня!', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (286, 'Ваш вес ... кг.', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (287, 'Первая мысль сегодня утром...', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (288, 'Кого вы ревнуете?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (289, 'Какой необычный сон вы видели в последнее время?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (290, 'Сегодня вы приняли решение...', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (291, 'Что вы сделали в последнее время чтобы приблизится к вашей цели?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (292, 'Чего вы сейчас жаждите?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (293, 'Какая полезная привычка вам бы сейчас не помешала?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (294, 'Лучший сценарий для романтического вечера?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (295, 'Ваш главный талант - это...', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (296, 'Можете ли вы сказать что у вас все есть?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (297, 'Что в своей внешности вы бы хотели изменить?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (298, 'Если бы вы собрались создать собственную команию, чем бы она занималась?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (299, 'Какое обещание вы дали и не выполнили?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (300, 'Ваша последняя ложь...', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (301, 'Вы успешнее, чем ваши сверстники?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (302, 'Ваш уровень владения иностранными языками...', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (303, 'В каком глупом споре вы сегодня учавствовали?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (304, 'В каком наряде вы были на Хеллоуние?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (305, 'Цитата дня...', 'ru');-----------------НОЯБРЬ-----------------
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (306, 'Какое блюдо вы в последний раз приготовили?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (307, 'Счастье - это...', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (308, 'Вы хорошо владеете компьютером?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (309, 'О чем вам нравится разговаривать?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (310, 'Какого рода замечания вы получаете чаще всего?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (311, 'Ваше любимое телевизионные шоу?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (312, 'В каком возрасте приходят самые гениальные идеи?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (313, 'Что вас заставляет двигаться дальше?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (314, 'В чем бы вам хотелось быть лучше других?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (315, 'Перчатки или варешки?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (316, 'Что бы вы посоветовали попробовать каждому?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (317, 'Кого недавно вы удалили из списка контактов?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (318, 'Какую книгу вы планируете прочесть в скором времени?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (319, 'Настоящая женщина никогда не...', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (320, 'Какой вопрос заставляет вас нервничать?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (321, 'Когда крайний раз вы ходили на танцы?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (322, 'Если вам нужно выбрать какой-то один момент из сегодняшнего дня, что вы выберете?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (323, 'Какая ваша самая большая мечта?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (324, 'Человек, с которым вы бы хотели проводить больше времени?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (325, 'В чем смысл жизни?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (326, 'Какой щедрый поступок вы совершили недавно?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (327, 'Самый ценный совет, который вы получили?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (328, 'О чем вы хотите спросить свою маму?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (329, 'Красота или ум?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (330, 'О чем вы больше всего сожалеете?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (331, 'Когда вы последний раз плакали? Почему?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (332, 'Сколько часов в день в среднем, вы тратите на сериалы?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (333, 'Какой самый продвинутыый гаджет у вас есть?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (334, 'Что в современной моде вас раздражает?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (335, 'Вы проспали. Свидание через 10 минут. Ваши действия...', 'ru'); -----------------ДЕКАБРЬ-----------------
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (336, 'На что вам не хватает смелости?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (337, 'Вам не нравится когда незнакомый человек...', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (338, 'Эпиграф в вашей автобиографии был бы такой...', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (339, 'На какой риск вы недавно пошли?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (340, 'Самое ужасное свидание - это...', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (341, 'На что вы тратие слишком много денег?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (342, 'Если бы вам дали 2 путевки в один конец в далекую страну, кого бы вы взяли с собой?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (343, 'Что вам мешает исполнить свою мечту?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (344, 'Лучшее начало дня - это...', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (345, 'Что вы делаете лучше других?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (346, 'Выходной. Интернет отключен на весь день. Что вы будете делать?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (347, 'Ваша любимая радиостанция?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (348, 'Момент, который вы бы хотели продлить?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (349, 'Какие темы для разговора вы считаете скучными?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (350, 'Какие три слова характеризуют вашу работу?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (351, 'Настоящий мужчина никогда не...', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (352, 'От какой привычки вам необходимо избавиться?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (353, 'Чем вы любите перекусить?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (354, 'Последнее время вы уходите с работы вовремя?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (355, 'Что удивило вас сегодня?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (356, 'Чего вам не достает в жизни?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (357, 'Чтобы вы сказали себе тринадцатилетней?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (358, 'Чтобы бы выхотели попробовать из того, что редко или никогда не кушали?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (359, 'Какое замечание вы чаще всего слышите от мамы или ближайших родственников?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (360, 'Главный сюрпиз года?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (361, 'Этот год в трех словах вы могли бы описать так...', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (362, 'Главное разочарование года - это...', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (363, 'В следующем году я обязательно...', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (364, 'С кем вы планируете встречать Новый Год?', 'ru');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (365, 'Ваше самое заветное воспоминание уходящего года...', 'ru');