INSERT INTO public.question_translation (question_id, question_text, language) VALUES (1, 'How, where and with whom you will celebrate New Year?', 'en');-----------------JANUARY-----------------
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (2, 'What is my goal for this year?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (3, 'How long do you have now your hair?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (4, 'In some awkward situation you recently got?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (5, 'Where do you live?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (6, 'What is a perfect day?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (7, 'Who do you want to be?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (8, 'What is unfortunate purchase you made lately?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (9, 'What now lies in your fridge?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (10, 'Where do you work?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (11, 'Are you popular?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (12, 'What is your main flaw?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (13, 'Who is the president?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (14, 'What a stupid thing you made today?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (15, 'Life is fair? Yes? No? Not today?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (16, 'What is your motto ...', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (17, 'On weekends you usually do ...', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (18, 'Do you miss ...', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (19, 'You want a new ...', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (20, 'How many cups of coffee you drink today?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (21, 'People can change?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (22, 'Your favorite song?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (23, 'You want to be are like ...', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (24, 'What is the biggest obstacle in front of you?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (25, 'Last time you laughed very much when ...', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (26, '3 rules for success ...', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (27, 'Your income is now ...', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (28, 'On a scale of 1 to 10 how you now feel sad? Why?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (29, 'What is your favorite accessory - it is ...', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (30, 'Who are the colleagues you have the best possible relations?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (31, 'What was important today?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (32, 'Career or family?', 'en');-----------------FEBRUARY-----------------
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (33, 'What would you like to know about your future?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (34, 'What sports do you do now?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (35, 'What do you want to get for your birthday?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (36, 'What compliment you did today?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (37, 'What is in your bag?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (38, 'What is the most important quality in your partner?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (39, 'The best time in your life?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (40, 'Why do you live where you live now?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (41, 'Today, you are most in need of ...', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (42, 'What is your weight?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (43, 'You should someone money? Or someone needs you?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (44, 'The best part of the day?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (45, 'Are you in Love?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (46, 'What is your most insane act done for love?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (47, 'Your prescription for the treatment of a broken heart?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (48, 'What is your position?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (49, 'How healthy do you feel, from 1 to 10?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (50, 'You are offended? If so, to whom?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (51, 'The most stylish thing in your wardrobe - it is ...', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (52, 'Now you want to rest or adventure?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (53, 'This person must ...', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (54, 'a friendship with the opposite sex is possible?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (55, 'Are you a leader or performer?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (56, 'What is the weather today?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (57, 'What are you reading?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (58, 'Describe your last night adventure ...', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (59, 'How much cash in your wallet? A bank account?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (60, 'In a restaurant you were last time?', 'en');-----------------MARCH-----------------
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (61, 'What kind of topics you are trying to avoid?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (62, 'What song is stuck in your head?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (63, 'Today was fun because ...', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (64, 'What is the performance or concert you attended recently?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (65, 'An interesting thing happened to you today?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (66, 'What talent would you like to possess?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (67, 'What you have presented on March 8?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (68, 'If you had to choose from what makes you happy, what one thing would you choose?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (69, 'This last time you gave something for no reason?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (70, 'What would you like to avoid in a relationship?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (71, 'Today was a difficult day because ...', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (72, 'Can you forgive infidelity?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (73, 'Without the invention of mankind you would not be able to live?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (74, 'The most expensive thing for you now - it is ...', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (75, 'How much do you feel beautiful, from 1 to 10?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (76, 'An interesting fact you learned recently?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (77, 'What interesting things happened today?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (78, 'How could you in three words to describe your personal life?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (79, 'What are you dreaming of now?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (80, 'When you were in a movie theater last time?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (81, 'What brand of clothing you mostly buy?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (82, 'What you do not have enough money?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (83, 'With whom would you like to switch places for a day?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (84, 'When dit you eat fast food last time?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (85, 'What do you like to do on a Sunday morning?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (86, 'Your main principle of life ...', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (87, 'How much time per day do you spend on telephone calls and personal correspondence?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (88, 'What can you buy for 1$?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (89, 'Where do you want to live?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (90, 'Your best friend is..', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (91, 'Funniest joke today?', 'en');-----------------APRIL-----------------
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (92, 'The most attractive actor?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (93, 'Bad idea - experiment with ...', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (94, 'If, in your day you can add a single hour, what would you spend it?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (95, 'You have a lot of spare time?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (96, 'Whose wedding you attended in the last time?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (97, 'What did you eat this morning?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (98, 'How many children you want to have?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (99, 'What are you currently working on?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (100, 'Three words that describe your condition now ...', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (101, 'You could do plastic surgery?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (102, 'You need a break? What for?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (103, 'What dream act which you do not have realized?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (104, 'What celebrity would you like to have dinner?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (105, 'What word parasite you are using now?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (106, 'About what you want to work?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (107, 'Who inspires you?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (108, 'What do you want to buy?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (109, 'What movie you watched recently?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (110, 'You are the original person? Why?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (111, 'What place on earth can be the name of paradise?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (112, 'How would you describe your behavior at work?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (113, 'When the last time you were sick?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (114, 'Are you an optimist or a pessimist?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (115, 'What is new you try today?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (116, 'Your ideal / credibility - it is ...', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (117, 'What color clothes do you prefer?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (118, 'What would you like to forget?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (119, 'In some celebrity would you like to interview?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (120, 'Most of all you are grateful for ...', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (121, 'What do you want to wait for later?', 'en');-----------------MAY-----------------
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (122, 'What time of the day you would like to beat?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (123, 'People you miss the most now?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (124, 'You want someone to take revenge?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (125, 'Who is the most brilliant man in your life?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (126, 'If tomorrow you can go on a trip anywhere, what place would you choose?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (127, 'Who do you feel appreciation today?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (128, 'What you do not have enough time?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (129, 'The new dish you learned to cook - it ...', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (130, 'What is act impressed me?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (131, 'You are on the right track?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (132, 'Who should play you in a movie about your life? What this film genre?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (133, '5 people with whom I most talk ...', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (134, 'What the pet you want to have?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (135, 'When and with whom in recent times you have had the most interesting conversation?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (136, 'Without some things you can not get out of the house?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (137, 'You tsinnik or metchtatel?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (138, 'When and under what circumstances you spoke to an audience last time?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (139, 'What I spend too much time?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (140, 'What I want to remember from now on?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (141, 'What is your height in ft?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (142, 'Are you satisfied with your life? From 1 to 10 ..', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (143, 'If you left one day, and with whom I would have spent it?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (144, 'Wherever I traveled in a time machine?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (145, 'How would you like to find your old age?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (146, 'Where and when the last time you swam?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (147, 'If today you do not have anything to do, what would you do?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (148, 'Which party did you last go?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (149, 'What color are your eyes and how they fit with your mood?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (150, 'When you last time was on a date?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (151, 'What is it, your dream vacation?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (152, 'How long do I make decisions?', 'en');-----------------JUNE-----------------
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (153, 'Which magazine or newspaper you read regularly?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (154, 'What you appreciate the boss?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (155, 'What problems excite you serious?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (156, 'What is unusual is in your bag?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (157, 'When did you last cry again?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (158, 'Today was mediocre? Why?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (159, 'Do you trust your instincts?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (160, 'Which singer is now the most popular?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (161, 'What size you buy clothes?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (162, 'When the last time you met with your friends?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (163, 'Do you have a secret passion? What?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (164, 'How do you like to spend your Friday night?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (165, 'Do you think you are like that literary hero ...', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (166, 'Who are the friends you want to be friends?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (167, 'How much you normally get up on weekdays?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (168, 'Perfect weekend - this is when ...', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (169, 'As usual you start a weekday?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (170, 'Who do you think dear?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (171, 'What makes you unhappy?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (172, 'Who is your best friend?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (173, 'Your biggest problem now - it is ...', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (174, '... Raises your spirits.', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (175, 'What perfume are you using these days?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (176, 'Today was a delightful day, because ...', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (177, 'What do you want to do, but did not and now regret?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (178, 'You kissed today? If so, with whom?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (179, 'What salary would suit you?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (180, 'If you could have a super power - it to be?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (181, 'When the last time you flew on an airplane?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (182, 'What would you like to know better?', 'en');-----------------JULY-----------------
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (183, 'What was the last personal letter that you received?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (184, 'What do you like most about your body?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (185, 'For that I appreciate my friends?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (186, 'When the last time you rested?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (187, 'What did you do today?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (188, 'Your recent thing that all rasmeshil?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (189, 'You can easily deduce from itself?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (190, 'Your enemy #1?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (191, 'How would you sum up the day in one sentence?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (192, 'What is unusual dish you tried?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (193, 'You made new friends?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (194, 'If you look around right now that you see?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (195, 'What area of ​​life you want to change?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (196, 'How much money you a month you spend on entertainment?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (197, 'Your favorite clothes ...', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (198, 'What role would you like to perform in the movie or the theater?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (199, 'How long are you going to work?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (200, 'Classic or casual?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (201, 'What are three sites you visit most often?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (202, 'Who you are?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (203, 'What can raise your mood right now?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (204, 'What do you like about your job?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (205, 'What is the buzz word you now come to mind?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (206, 'To impress a new friend, you ...', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (207, 'Your first thought in the morning ...', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (208, 'Who are you jealous?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (209, 'What upset you today?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (210, 'Would you prefer to live in the city or the countryside?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (211, 'What you are able to move?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (212, 'You order at home?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (213, 'What is your favorite gadget?', 'en');-----------------AUGUST-----------------
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (214, 'Which team do you support? (Any sport)', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (215, 'What food the last time someone cooked for you?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (216, 'What would you like to receive a gift from a loved one?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (217, 'You are an intelligent man? On a scale of 1 to 10.', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (218, 'What are you most afraid of?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (219, 'What are the 5 things you would take to a desert island?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (220, 'Do you feel lonely?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (221, 'Where do you see yourself in a year?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (222, 'The best news today ...', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (223, 'What irritates you in others?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (224, 'How would you describe your look?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (225, 'The first word came to mind?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (226, 'How much time do you spend on social networks?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (227, 'What you need to throw away?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (228, 'From whom would you like to receive SMS right now?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (229, 'How much money are you willing to spend on clothes?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (230, 'How much time do you spend on a dream?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (231, 'Who you angry today?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (232, 'What you need to do to achieve the desired?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (233, 'Your weak point - it ...', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (234, 'Your plans for tomorrow ...', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (235, 'Your secret?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (236, 'What are you currently obsessed with?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (237, 'When was the last time you ate a pizza? What was she like?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (238, 'If you ever write a book about you, what name it will have?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (239, 'How much time do you spend on the way to work?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (240, 'Do you have a mascot?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (241, 'Plan or improvisation?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (242, 'When you often come to mind a good idea?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (243, 'The best thing that happened this summer?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (244, 'How much money have you spent on your last vacation?', 'en');-----------------SEPTEMBER-----------------
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (245, 'What can bring you out of yourself?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (246, 'Love is...', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (247, 'What is for dinner?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (248, 'Are you tired of your job?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (249, 'What recently viewed the movie you would not recommend to friends?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (250, 'What shocking news recently, you know?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (251, 'You do not have the patience to ...', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (252, 'You would not want that would you now ... it was years because ...', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (253, 'What thoughts you are pursuing at the moment?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (254, 'How could you in three words describe your job?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (255, 'From the last missed call on my phone?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (256, 'How would your friend describe you in three words?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (257, 'How many countries have you been?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (258, 'What do you consider your greatest achievement?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (259, 'What do you spend too much money?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (260, 'For that you first pay attention to when meeting with a stranger?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (261, 'Your recipe for a good mood?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (262, 'If you moshli turn back time, what would you change?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (263, 'You have found proof of the existence of a higher power?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (264, 'When you drank alcohol last time?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (265, 'What gives you the greatest pleasure?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (266, 'You know how to say "no"?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (267, 'Today was a fun day, because ...', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (268, 'What profession would you like to try yourself?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (269, 'That should remain as it is?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (270, 'What / who associated with the most pleasant memories?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (271, 'The bad news: it is better to embellish or lay out as it is?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (272, 'You often lying?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (273, 'What time you went to bed last night?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (274, 'What do you see yourself in a year?', 'en');-----------------OCTOBER-----------------
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (275, 'Who is the most important person in your life?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (276, 'What do you consider an insurmountable?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (277, 'Who would you like to be in the next life?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (278, 'When was the last time you went out of town?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (279, 'Can you first talk / meet with a stranger?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (280, 'What song describes you?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (281, 'The food you abuse ...', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (282, 'Last spontaneous act? What consequences?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (283, 'Do you have a loved one?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (284, 'What is the secret of successful love relationships?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (285, 'Joke of the Day!', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (286, 'Your weight ... kg.', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (287, 'The first thought this morning ...', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (288, 'Who are you jealous?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (289, 'What an extraordinary dream you have seen lately?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (290, 'Today you have decided to ...', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (291, 'What have you done lately to get closer to your goal?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (292, 'What are you now crave?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (293, 'What good habit you have now is not prevented?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (294, 'The best scenario for a romantic evening?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (295, 'What is your main talent - it is ...', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (296, 'Can you say that you have everything?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (297, 'What is in your appearance you want to change?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (298, 'If you are going to create your own Tweet, what would she do?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (299, 'What is the promise you have given and have not fulfilled?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (300, 'Your last lie ...', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (301, 'Are you better than your peers?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (302, 'Your proficiency in foreign languages ​​...', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (303, 'What a stupid argument today you participated?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (304, 'What outfit were you on Hellounie?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (305, 'Quote of the Day...', 'en');-----------------NOVEMBER-----------------
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (306, 'What dish the last time you cooked?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (307, 'Happiness is...', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (308, 'You have a way with computers?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (309, 'What do you like to talk?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (310, 'What kind of comments do you get most often?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (311, 'Your favorite television show?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (312, 'At what age is the most brilliant ideas come?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (313, 'What makes you move on?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (314, 'What would you like to be better than others?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (315, 'Gloves or vareshki?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (316, 'What would you suggest everyone to try?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (317, 'Whom you have recently deleted from your contact list?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (318, 'What book do you plan to read in a short time?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (319, 'This woman has never ...', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (320, 'What question makes you nervous?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (321, 'When the last time you went to the dance?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (322, 'If you have to choose any one moment of the day, what you choose?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (323, 'What is your biggest dream?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (324, 'The person with whom you would like to spend more time?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (325, 'What is the meaning of life?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (326, 'What a generous act you made recently?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (327, 'The most valuable advice that you have received?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (328, 'What do you want to ask your mom?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (329, 'Beauty or the mind?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (330, 'What is your biggest regret?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (331, 'When did you last cry? Why?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (332, 'How many hours a day on average, do you spend on the series?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (333, 'What is the prodvinutyy gadget you have?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (334, 'What is in a modern fashion annoys you?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (335, 'You overslept. Rendezvous after 10 minutes. Your actions...', 'en');-----------------DECEMBER-----------------
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (336, 'What you do not have the guts?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (337, 'You do not like it when a stranger ...', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (338, 'The epigraph in your autobiography would be a ...', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (339, 'At what risk you have recently gone?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (340, 'The worst thing a date - it is ...', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (341, 'What do you spend too much money?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (342, 'If you were given 2 vouchers at one end into a far country, who would you take with you?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (343, 'What is stopping you to fulfill your dream?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (344, 'The best start to the day - it is ...', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (345, 'What do you do better than others?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (346, 'Output. Internet off for the whole day. What are you going to do?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (347, 'Your favorite radio station?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (348, 'The moment that you would like to extend?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (349, 'What topic of conversation do you consider boring?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (350, 'What three words describe your work?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (351, 'This man never ...', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (352, 'From a habit you need to get rid of?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (353, 'What do you like to eat?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (354, 'Last time you go to work on time?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (355, 'What surprised you today?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (356, 'What you lack in life?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (357, 'So you said to yourself, thirteen?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (358, 'What would you like to try out the fact that rarely or never ate?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (359, 'What comment do you most often hear from mothers or close relatives?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (360, 'The main surprise of the year?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (361, 'This year, in three words would you describe this ...', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (362, 'The main disappointment of the year - it is ...', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (363, 'The next year, I will definitely ...', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (364, 'Who do you plan to celebrate the New Year?', 'en');
INSERT INTO public.question_translation (question_id, question_text, language) VALUES (365, 'Your fondest memory of the passing year ...', 'en');